// ElevenLabs as the engine for the owner's own voice (opt-in, their own API
// key). The recorded sample becomes an instant voice clone in their ElevenLabs
// account; lines are then generated by Eleven v4. Unlike the on-Mac engine, the
// sample and every line go to ElevenLabs, and the settings say so.
import { app } from "electron";
import { existsSync, rmSync } from "node:fs";
import path from "node:path";
import { readSealed, writeSealed } from "../../sealed.js";

const API = "https://api.elevenlabs.io/v1";

/** The owner's key and the clone made from their current sample (re-cloned when the sample changes). */
export type ElevenAccount = { apiKey: string; voiceId: string | null; sampleId: string | null };

const file = () => path.join(app.getPath("userData"), "elevenlabs.bin");

export function loadEleven(): ElevenAccount | null {
  if (!existsSync(file())) return null;
  try { return JSON.parse(readSealed(file()).toString("utf8")) as ElevenAccount; } catch { return null; }
}

export const saveEleven = (a: ElevenAccount) => writeSealed(file(), JSON.stringify(a));
export const clearEleven = () => rmSync(file(), { force: true });

/**
 * The owner's expressiveness setting (0.3 steady .. 0.9 lively) as ElevenLabs
 * voice settings: livelier means less stability and more style (pure).
 */
export function voiceSettingsFor(expressiveness: number) {
  const t = Math.min(1, Math.max(0, (expressiveness - 0.3) / 0.6));
  const round = (x: number) => Math.round(x * 100) / 100;
  return { stability: round(0.75 - 0.5 * t), similarity_boost: 0.85, style: round(0.6 * t), use_speaker_boost: true };
}

async function call(apiKey: string, pathname: string, init: RequestInit, fetcher: typeof fetch): Promise<Response> {
  const res = await fetcher(`${API}${pathname}`, { ...init, headers: { "xi-api-key": apiKey, ...init.headers }, signal: AbortSignal.timeout(90000) })
    .catch(() => null);
  if (!res) throw new Error("Couldn't reach ElevenLabs. Check your connection and try again.");
  if (res.status === 401) throw new Error("ElevenLabs didn't accept the API key. Paste a new one from elevenlabs.io, Developers, API keys.");
  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as { detail?: { message?: string } | string };
    const detail = typeof body.detail === "string" ? body.detail : body.detail?.message;
    throw new Error(`ElevenLabs said no${detail ? `: ${detail}` : ` (${res.status})`}.`);
  }
  return res;
}

/** Checks the key works before it's saved. */
export async function checkKey(apiKey: string, fetcher: typeof fetch = fetch): Promise<void> {
  await call(apiKey, "/user", { method: "GET" }, fetcher);
}

/** Makes an instant voice clone from the sample (WAV). ElevenLabs may ask the owner to verify it's their voice. */
export async function cloneVoice(apiKey: string, name: string, wav: Buffer, fetcher: typeof fetch = fetch): Promise<{ voiceId: string; requiresVerification: boolean }> {
  const form = new FormData();
  form.append("name", name);
  form.append("description", "Made by Peguin from a sample recorded with the owner's consent.");
  form.append("remove_background_noise", "true");
  form.append("files", new Blob([new Uint8Array(wav)], { type: "audio/wav" }), "sample.wav");
  const res = await call(apiKey, "/voices/add", { method: "POST", body: form }, fetcher);
  const data = (await res.json()) as { voice_id?: string; requires_verification?: boolean };
  if (!data.voice_id) throw new Error("ElevenLabs didn't return a voice. Try again.");
  return { voiceId: data.voice_id, requiresVerification: !!data.requires_verification };
}

/** Best effort: removes an old clone from the owner's ElevenLabs account. */
export async function deleteVoice(apiKey: string, voiceId: string, fetcher: typeof fetch = fetch): Promise<void> {
  await call(apiKey, `/voices/${encodeURIComponent(voiceId)}`, { method: "DELETE" }, fetcher).catch(() => {});
}

/** One line as 24 kHz WAV, the same format the on-Mac engine makes. */
export async function speakWav(
  apiKey: string, voiceId: string, text: string, o: { model: string; expressiveness: number }, fetcher: typeof fetch = fetch,
): Promise<Buffer> {
  const res = await call(apiKey, `/text-to-speech/${encodeURIComponent(voiceId)}?output_format=wav_24000`, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "audio/wav" },
    body: JSON.stringify({ text, model_id: o.model, voice_settings: voiceSettingsFor(o.expressiveness) }),
  }, fetcher);
  return Buffer.from(await res.arrayBuffer());
}
